//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOL_Patricia_Curo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        public int IdPrestamo { get; set; }
        public int IdLibro { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> Duración { get; set; }
        public Nullable<int> TipoPrestamo { get; set; }
        public System.DateTime FechaDev { get; set; }
    
        public virtual Libro Libro { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual TipoPrestamo TipoPrestamo1 { get; set; }
    }
}
